##
---
- hosts: localhost
  name: NSX 3.1.x Deployment
  gather_facts: false
  vars_files:
    - answerfile.yml


# Infrastructure Deployment #

- ansible.builtin.ansible.builtin: playbooks/3.1/01-deploy-nsxmanager.yml
- ansible.builtin.import_playbook: playbooks/3.1/02-configure-nsxmanager-vip.yml
- ansible.builtin.import_playbook: playbooks/3.1/03-configure-nsxmanager-license.yml
- ansible.builtin.import_playbook: playbooks/3.1/04-configure-compute-managers.yml
- ansible.builtin.import_playbook: playbooks/3.1/05-configure-nsxmanager-uplinkprofiles.yml
- ansible.builtin.import_playbook: playbooks/3.1/06-configure-nsxmanager-ippools.yml
- ansible.builtin.import_playbook: playbooks/3.1/07-configure-nsxmanager-transportzones.yml
- ansible.builtin.import_playbook: playbooks/3.1/08-configure-nsxmanager-transportnodesprofiles.yml
- ansible.builtin.import_playbook: playbooks/3.1/09-configure-nsxmanager-transportnodes.yml
- ansible.builtin.import_playbook: playbooks/3.1/10-deploy-edgenodes.yml
- ansible.builtin.import_playbook: playbooks/3.1/11-configure-nsxmanager-edgeclusters.yml

## Would suggest running the next section seperate from above - Need to give time for Edge Clusters to populate.  
## Playbook 11 has a pause that can be enabled

- ansible.builtin.import_playbook: playbooks/12-create-edge-bridge-profiles
- ansible.builtin.import_playbook: playbooks/13-create-vlan-segments
- ansible.builtin.import_playbook: playbooks/14-create-tier0-gateways
- ansible.builtin.import_playbook: playbooks/15-create-tier1-gateways
- ansible.builtin.import_playbook: playbooks/16-create-segments
- ansible.builtin.import_playbook: playbooks/17-deploy-nsxmanager-cluster.yml       ## This can run anytime AFTER 04-configure-compute-mangers - It relies on a Compute Manager being defined
...
