---
- hosts: localhost
  name: 11 - Create NSX Edge Clusters
  gather_facts: false
  vars_files:
    - ../../answerfile.yml

  tasks:
    - name: Creating Edge Clusters
      vmware.ansible_for_nsxt.nsxt_edge_clusters:
        hostname: "{{ nsx_hostname }}.{{ nsx_domain }}"
        username: "{{ nsx_admin_user }}"
        password: "{{ nsx_admin_password }}"
        validate_certs: "{{ nsx_validate_certs }}"
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        cluster_profile_bindings: "{{ item.cluster_profile_bindings }}"
        members: "{{ item.members }}"
        state: "{{ state }}"
      with_items:
        - "{{ edge_clusters }}"

    # - name: Pausing 1 minute for Edge Clusters to fully populate
    #   ansible.builtin.pause:
    #     seconds: 60
...
