---
- hosts: localhost
  name: 04 - Remove NSX Transport Zones
  gather_facts: false
  vars_files:
    - ../../answerfile.yml

  tasks:
    - name: Remove NSX Transport Zones
      vmware.ansible_for_nsxt.nsxt_transport_zones:
        hostname: "{{ nsx_hostname }}.{{ nsx_domain }}"
        username: "{{ nsx_admin_user }}"
        password: "{{ nsx_admin_password }}"
        validate_certs: "{{ nsx_validate_certs }}"
        resource_type: "TransportZone"
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        # host_switch_mode: "STANDARD" # PRE 3.2
        tz_type: "{{ item.tz_type }}"
        state: "{{ state }}"
      with_items:
        - "{{ transportzones }}"
...
