---
- hosts: localhost
  name: 06 - Remove NSX Uplink Profiles
  gather_facts: false
  vars_files:
    - ../../answerfile.yml

  tasks:
    - name: Remove Uplink Profiles
      vmware.ansible_for_nsxt.nsxt_uplink_profiles:
        hostname: "{{ nsx_hostname }}.{{ nsx_domain }}"
        username: "{{ nsx_admin_user }}"
        password: "{{ nsx_admin_password }}"
        validate_certs: "{{ nsx_validate_certs }}"
        resource_type: "UplinkHostSwitchProfile"
        display_name: "{{ item.display_name }}"
        teaming: "{{ item.teaming }}"
        transport_vlan: "{{ item.transport_vlan }}"
        state: "{{ state }}"
      with_items:
        - "{{ uplink_profiles }}"
...
