---
- hosts: 127.0.0.1
  name: 08 - Remove NSX VIP (Virtual IP Address)
  gather_facts: false
  vars_files:
    - ../../answerfile.yml

  tasks:
    - name: Remove NSX Manager VIP
      vmware.ansible_for_nsxt.nsxt_virtual_ip:
        hostname: "{{ nsx_hostname }}.{{ nsx_domain }}"
        username: "{{ nsx_admin_user }}"
        password: "{{ nsx_admin_password }}"
        validate_certs: "{{ nsx_validate_certs }}"
        virtual_ip_address: "{{ nsx_vip }}"
        state: "{{ state }}"
...
