---
- hosts: localhost
  name: 04 - Register a vCenter as a Compute Manager in NSX
  gather_facts: false
  vars_files:
    - ../answerfile.yml

  tasks:
    - name: Register Compute Managers
      vmware.ansible_for_nsxt.nsxt_fabric_compute_managers:
        hostname: "{{ nsx_hostname }}.{{ nsx_domain }}"
        username: "{{ nsx_admin_user }}"
        password: "{{ nsx_admin_password }}"
        validate_certs: "{{ nsx_validate_certs }}"
        display_name: "{{ item.display_name }}"
        server: "{{ item.server }}"
        origin_type: "{{ item.origin_type }}"
        credential: "{{ item.credentials }}"
        state: "{{ state }}"
      with_items:
        - "{{ compute_managers }}"
...
