---
- hosts: localhost
  name: 09 - Configure NSX Transport Node Collection
  gather_facts: false
  vars_files:
    - ../answerfile.yml

  tasks:
    - name: Create Transport Node Collection
      vmware.ansible_for_nsxt.nsxt_transport_node_collections:
        hostname: "{{ nsx_hostname }}.{{ nsx_domain }}"
        username: "{{ nsx_admin_user }}"
        password: "{{ nsx_admin_password }}"
        validate_certs: "{{ nsx_validate_certs }}"
        display_name: "{{ item.display_name | default(required) }}"
        resource_type: "TransportNodeCollection"
        description: "{{ item.description | default(omit) }}"
        compute_manager_name: "{{ item.compute_manager_name }}"
        cluster_name: "{{ item.cluster_name }}"
        transport_node_profile_name: "{{ item.transport_node_profile_name }}"
        state: "{{ state }}"
      with_items:
        - "{{ host_transport_nodes }}"
...
