---
- hosts: 127.0.0.1
  name: 15 - Create Tier1 Gateways
  gather_facts: false
  vars_files:
    - ../../answerfile.yml

  tasks:
    - name: Create Tier0 Gateway
      vmware.ansible_for_nsxt.nsxt_policy_tier1:
        hostname: "{{ nsx_hostname }}.{{ nsx_domain }}"
        username: "{{ nsx_admin_user }}"
        password: "{{ nsx_admin_password }}"
        validate_certs: "{{ nsx_validate_certs }}"
        display_name: "{{ item.display_name }}"
        tier0_display_name: "{{ item.tier0_display_name | default(omit) }}"
        locale_services: "{{ item.locale_services | default(omit) }}"
        route_advertisement_types: "{{ item.route_advertisement_types | default(omit) }}"
        state: "{{ state }}"
      with_items:
        - "{{ tier1 }}"
...
