---
- hosts: 127.0.0.1
  name: 12 - Deploy the NSX Managers to a cluster
  gather_facts: false
  vars_files:
    - ../../answerfile.yml

  tasks:
    - name: Deploying NSX Manager OVA and adding to cluster - This operation will take some time
      vmware.ansible_for_nsxt.nsxt_manager_auto_deployment:
        hostname: "{{ nsx_hostname }}.{{ nsx_domain }}"
        username: "{{ nsx_admin_user }}"
        password: "{{ nsx_admin_password }}"
        validate_certs: "{{ nsx_validate_certs }}"
        deployment_requests:
        - roles:
          - CONTROLLER
          - MANAGER
          form_factor: "{{ item.nsx_size }}"
          user_settings: "{{ item.user_settings }}"
          deployment_config: "{{ item.deployment_config }}"
        state: "{{ state }}"
      with_items:
        - "{{ addional_nsx_managers }}"
...
